### ISSUE TITLE
Fail safe in offboard mode

### ISSUE THREAD

**Issue by PeymanAmirii** [PX4/PX4-user_guide#1690]
If we set parameter COM_RCL_EXCEPT as 2, the firmware considers offboard mode "in which RC loss is ignored and the failsafe action not triggered". I set the parameter as 2 but I face this  message when I run offboard codes such as the standard example "offboard_velocity_ned.py" and doesn't let the drone fly:

WARN  [commander] Failsafe enabled: No manual control stick input	
INFO  [commander] Failsafe mode activated	
INFO  [tone_alarm] battery warning (fast)
INFO  [commander] Disarmed by auto preflight disarming	
INFO  [logger] closed logfile, bytes written: 7697312
INFO  [navigator] RTL HOME activated	
INFO  [commander] Failsafe mode deactivated

It seems that px4 doesn't recognize that offboard mode is being used in our flight Python codes.

If we assign 4 to parameter COM_RCL_EXCEPT, failsafe is deactivated completely and the drone flies. However, we want failsafe to activate when "offboard link is lost while under Offboard control" as mentioned here:
https://docs.px4.io/master/en/config/safety.html#offboard-loss-failsafe
This is why we want failsafe mode not  to be deactivated completely using 4 as COM_RCL_EXCEPT.

**Comment by hamishwillee** [comment]
Did you actually set `COM_RCL_EXCEPT` as 2 (decimal)? If so that is 10 binary, which means that you're disabling the RC exception in hold mode, not offboard mode. If you set to 4 then you will be disabling the RC failsafe for offboard mode.

But the stuff in https://docs.px4.io/master/en/config/safety.html#offboard-loss-failsafe should still trigger fine if you lose the offboard link.

This area is for documentation issues, and what you're talking about here is not a docs issue. So I'm closing. If I'm wrong and the docs are saying something wrong, then please reopen.
